### ISSUE TITLE
Feature: Make Player screen work on single song

### ISSUE THREAD

**Issue by Vladuken** [ArtemShishko/internship#49]
When you click on real song you navigate to this screen
This screen should be able to:
- Play/Pause song
- Rewind song
- Play Pause song from Notification #50

**Comment by ArtemShishko** [comment]
Estimation: 3h+

**Comment by Vladuken** [comment]
1. Remove all useless code, that is doing nothing
2. Change most of classes to DI and Inject, where you can (for now make all in PlayerModule)
3. Prepare scheme of these classes (you can use draw.io, but i think that on paper it will be faster and simpler). Do this scheme as simple as you can - main idea is to get knoledge of which classes knows about each other
